# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHXvaxPqzoLTOAHMAtEVCmg_DW_uJsfh
"""

# Download the files
!wget https://zenodo.org/api/records/5502543/files-archive -O repository_name.zip

# Unzip
!unzip repository_name.zip -d /content

# Delete repository_name.zip from /content
!rm /content/repository_name.zip

# Columns of the dataframe
columns = []
for i in range(1, 31):
  columns.append('eta_rel_' + str(i))
  columns.append('phi_rel_' + str(i))
  columns.append('pt_rel_' + str(i))
  columns.append('mask_' + str(i))

# Read files as dataframes
import pandas as pd

df_g = pd.read_csv('g_jets.csv', decimal = '.', sep = " ", names = columns) # for gluon jets, for example